app:
  name: QuarryVision
db:
  url: jdbc:postgresql://localhost:5432/qv
  user: postgres
  pass: secret

import:
  inbox: E:/INBOX
  source: F:/USB
  patterns:
    - "*.mp4"
    - "*.mkv"
    - "*.ts"
