app:
  name: QuarryVision
db:
  url: jdbc:postgresql://localhost:5432/quarryvision
  user: quarry
  pass: quarry

import:
  inbox: E:/INBOX
  source: F:/USB
  patterns:
    - "*.mp4"
    - "*.mkv"
    - "*.ts"
detect:
  stepFrames: 15
  diffThreshold: 45
  eventRatio: .16

  cooldownFrames: 150
  minChangedPixels: 35000
  morphKernel: { w: 1.5, h: 1.5}
  emaAlpha: 0.45       # быстрее падение EMA
  thrLowFactor: 0.96   # раньше выходим из ACTIVE
  minActiveMs: 300      # не резать слишком коротко
  nmsWindowMs: 700   # меньше подавление соседних пиков
  mergeMs: 2500        # события ближе этого окна считаем одной погрузкой
  trace: false
# OCR (Tesseract / Tess4J)
ocr:
  enabled: true
  # Путь к каталогу с *.traineddata. Можно абсолютный или относительный
  datapath: "./tessdata"
  # Список языков через '+', напр. "eng+rus"
  languages: "eng+rus"
  # Уровень Page Segmentation Mode (PSM). 7 -- одна строка текста.
  psm: 7
  # OEM: 1 -- LSTM only, 3 -- default (поиск лучшего)
  oem: 3

