app:
  name: QuarryVision
db:
  url: jdbc:postgresql://localhost:5432/qv
  user: postgres
  pass: secret

import:
  inbox: E:/INBOX
  source: F:/USB
  patterns:
    - "*.mp4"
    - "*.mkv"
    - "*.ts"
detect:
  stepFrames: 15
  diffThreshold: 45
  eventRatio: 0.14
  cooldownFrames: 120
  minChangedPixels: 25000
  morphKernel:
    w: 3
    h: 3