blank_issues_enabled: false
contact_links:
  - name: ❓ Вопрос по использованию
    url: https://github.com/Bakhman/quarry-vision/discussions
    about: Задай вопрос или обсуди идею в разделе Discussions
