blank_issues_enabled: false
contact_links:
  - name: 💬 Общие вопросы
    url: https://github.com/Bakhman/quarry-vision/discussions
    about: Задай вопрос или обсуди идею в разделе Discussions

  - name: ❓ Вопрос по использованию
    url: https://github.com/Bakhman/quarry-vision/discussions/categories/help
    about: Вопросы по установке, настройке и запуску QuarryVision

  - name: 💡 Идеи и предложения
    url: https://github.com/Bakhman/quarry-vision/discussions/categories/идеи-и-предложения
    about: Предлагай улучшения и новые функции для QuarryVision
