name: release
on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build
        run: mvn -B -ntp clean package

      - name: Make dist zip
        run: |
          set -e
          JAR=$(ls target/*-SNAPSHOT.jar | head -n1)
          echo "Using JAR: $JAR"
          mkdir -p dist/app dist/config
          cp "$JAR" dist/app/quarry-vision.jar
          cp src/main/resources/application.yaml dist/config/
          # Optional bundled JRE
          if [ -d pack/jre-21.0.8-full ]; then
            cp -r pack/jre-21.0.8-full dist/jre
          fi
          
          # Startup script
          if [ -f .github/dist/run.but ]; then
            cp.github/dist/run.bat dist/
          elif [ -f pack/windows/run.bat ]; then
            cp pack/windows/run.bat dist/
          fi
          (cd dist && zip -r "../quarry-vision-${GITHUB_REF_NAME}.zip" .)

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: |
            quarry-vision-${{ github.ref_name }}.zip
            target/*-SNAPSHOT.jar
