name: release
on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build
        run: mvn -B -ntp clean package

      - name: Make dist zip
        run: |
          set -e
          JAR=$(ls target/*-SNAPSHOT.jar | head -n1)
          echo "Using JAR: $JAR"
          mkdir -p dist/app dist/config
          cp "$JAR" dist/app/quarry-vision.jar
          cp src/main/resources/application.yaml dist/config/
          # include runtime and startup script
          cp -r pack/jre-21.0.8-full dist/jre || echo "jre folder not found, skipping"
          cp pack/windows/run.bat || true
          
          cd dist
          zip -r ../quarry-vision-${GITHUB_REF_NAME}.zip .
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: |
            quarry-vision-${{ github.ref_name }}.zip
            target/*-SNAPSHOT.jar
