name: release
on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build
        run: mvn -B -ntp -DskipTests clean package

      # Устанавливаем Liberica JRE Full (с JavaFX) через Chocolatey
      - name: Install JRE with JavaFX (Azul Zulu FX)
        shell: pwsh
        run: |
          choco install -y zulu21-jre-fx || choco install -y zulu17-jre-fx
          $roots = @('C:\Program Files\Zulu', 'C:\Program Files (x86)\Zulu')
          $jre = $null
          foreach ($r in $roots) {
            if (Test-Path $r) {
              $cands = Get-ChildItem $r -Directory -ErrorAction SilentlyContinue | Where-Object { $_.Name -match 'zulu-(21|17).*-jre' }
              foreach ($d in $cands) {
                if (Test-Path "$($d.FullName)\bin\javaw.exe") { $jre = $d.FullName; break }
              }
            }
            if ($jre) { break }
          }
          if (-not $jre) { throw "Zulu JRE FX not found" }
          "JRE_DIR=$jre" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Make dist
        shell: pwsh
        run: |
          $jar = (Get-ChildItem target\*.jar | Where-Object { $_.Name -notmatch 'sources|javadoc|tests' } | Select-Object -First 1)
          if (-not $jar) { throw "Jar not found" }
          New-Item -ItemType Directory -Force -Path dist\app, dist\config | Out-Null
          Copy-Item $jar.FullName dist\app\quarry-vision.jar
          Copy-Item src\main\resources\application.yaml dist\config\
          Copy-Item .github\dist\run.bat dist\
          Copy-Item -Recurse -Force "$env:JRE_DIR" dist\jre

      - name: Zip dist
        shell: pwsh
        run: |
          Compress-Archive -Path dist\* -DestinationPath "quarry-vision-$env:GITHUB_REF_NAME.zip" -Force
          Get-FileHash "quarry-vision-$env:GITHUB_REF_NAME.zip" -Algorithm SHA256 | ForEach-Object { $_.Hash } | Out-File -Encoding ascii "quarry-vision-$env:GITHUB_REF_NAME.zip.sha256"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: |
            quarry-vision-${{ github.ref_name }}.zip
            quarry-vision-${{ github.ref_name }}.zip.sha256
            target\*.jar
