name: release
on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Export tag name
        run: echo "GITHUB_REF_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Check env seen by Maven
        run: mvn -q help:evaluate -Dexpression=env.GITHUB_REF_NAME -DforceStdout

      - name: Build fat JAR
        run: mvn -B -ntp -DskipTests clean package

      - name: Prepare dist structure
        run: |
          set -e
          mkdir -p dist/app dist/config
          JAR=$(python3 -c "import glob,os,sys; c=[p for p in glob.glob('target/quarry-vision-*.jar') if not os.path.basename(p).startswith('original-')]; sys.exit(1) if not c else print(max(c, key=os.path.getmtime))")
          echo "Resolved shaded JAR: $JAR"
          cp "$JAR" dist/app/quarry-vision.jar
          cp src/main/resources/application.yaml dist/config/
          [ -f .github/dist/run.bat ] && cp .github/dist/run.bat dist/

      - name: Bundle Liberica JRE 21 Full (Windows)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $urls = @(
            'https://download.bell-sw.com/java/21.0.8+12/bellsoft-jre21.0.8+12-windows-amd64-full.zip',
            'https://download.bell-sw.com/java/21.0.7+9/bellsoft-jdk21.0.7+9-windows-amd64-full.zip',
            'https://download.bell-sw.com/java/21.0.5+11/bellsoft-jre21.0.5+11-windows-amd64-full.zip',
            'https://download.bell-sw.com/java/21.0.4+7/bellsoft-jre21.0.4+7-windows-amd64-full.zip'
          )
          $ok = $false
          foreach ($u in $urls) {
            Write-Host "Trying $u"
            try {
              Invoke-WebRequest $u -OutFile jre.zip -TimeoutSec 120
              $ok = $true; break
            } catch {
              Write-Host "Failed: $($_.Exception.Message)"
            }
          }
          if (-not $ok) { throw 'No working Liberica JRE Full URL' }
          Expand-Archive -Path jre.zip -DestinationPath dist -Force
          $jreDir = Get-ChildItem dist -Directory | Where-Object { Test-Path "$($_.FullName)\bin\java.exe" } | Select-Object -First 1
          if (-not $jreDir) { throw 'Liberica JRE Full not found after extract' }
          if (Test-Path dist\jre) { Remove-Item -Recurse -Force dist\jre }
          Rename-Item -Path $jreDir.FullName -NewName 'jre'

      - name: Make ZIP
        run: |
          cd dist
          zip -r "../quarry-vision-${GITHUB_REF_NAME}.zip" .
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: |
            quarry-vision-${{ github.ref_name }}.zip
            target/*-SNAPSHOT.jar
