name: release
on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build fat JAR
        run: mvn -B -ntp -DskipTests clean package

      - name: Prepare dist structure
        run: |
          set -e
          mkdir -p dist/app dist/config
          JAR=$(ls target/*-SNAPSHOT.jar | head -n1)
          echo "Using JAR: $JAR"
          cp "$JAR" dist/app/quarry-vision.jar
          cp src/main/resources/application.yaml dist/config/
          if [ -f .github/dist/run.bat ]; then
            cp .github/dist/run.bat dist/
          fi

      - name: Bundle Liberica JRE 21 Full (Windows)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $url = 'https://download.bell-sw.com/java/21.0.4+7/bellsoft-jre21.0.4+7-windows-amd64-full.zip'
          Invoke-WebRequest $url -OutFile jre.zip
          Expand-Archive -Path jre.zip -DestinationPath dist -Force
          $jreDir = Get-ChildItem dist -Directory |
            Where-Object { Test-Path "$($_.FullName)\bin\java.exe" } |
            Select-Object -First 1
          if (-not $jreDir) { throw 'Liberica JRE Full not found after extract' }
          if (Test-Path dist\jre) { Remove-Item -Recurse -Force dist\jre }
          Rename-Item -Path $jreDir.FullName -NewName 'jre'

      - name: Make ZIP
        run: |
          cd dist
          zip -r "../quarry-vision-${GITHUB_REF_NAME}.zip" .
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: |
            quarry-vision-${{ github.ref_name }}.zip
            target/*-SNAPSHOT.jar
