name: release
on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build
        run: mvn -B -ntp clean package

      # Скачиваем JRE для Windows, чтобы не хранить в репо
      - name: Download Windows JRE 17 (Temurin)
        run: |
          set -euo pipefail
          curl -L -o jre.zip https://api.adoptium.net/v3/binary/latest/17/ga/windows/x64/jre/hotspot/normal/eclipse
          unzip -q jre.zip -d .github/pack/
          mv "$(ls -d .github/pack/jdk-17* | head -n1)" .github/pack/jre-17


      - name: Make dist zip
        run: |
          set -euo pipefail
          JAR=$(ls target/*.jar | grep -vE '(sources|javadoc|tests)' | head -n1)
          echo "Using JAR: $JAR"
          mkdir -p dist/app dist/config
          cp "$JAR" dist/app/quarry-vision.jar
          cp src/main/resources/application.yaml dist/config/
          # Bundled JRE
          if [ -d .github/pack/jre-17 ]; then
            cp -r .github/pack/jre-17 dist/jre
          fi
          
          # Startup script (исправленные пути и опечатки)
          if [ -f .github/dist/run.bat ]; then
            cp .github/dist/run.bat dist/
          elif [ -f .github/pack/windows/run.bat ]; then
            cp .github/pack/windows/run.bat dist/
          else
            echo "ERROR: run.bat not found" >&2
            exit 1
          fi
          (cd dist && zip -r "../quarry-vision-${GITHUB_REF_NAME}.zip" .)

      - name: Checksums
        run: |
          sha256sum "quarry-vision-${GITHUB_REF_NAME}.zip" > "quarry-vision-${GITHUB_REF_NAME}.zip.sha256"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: |
            quarry-vision-${{ github.ref_name }}.zip
            target/*.jar
            quarry-vision-${{ github.ref_name }}.zip.sha256