name: release
on:
  push:
    tags:
      - "v*"

jobs:
  build-zip:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build
        run: mvn -B -ntp clean package
      - name: Make dist zip
        run: |
          mkdir -p dist/app dist/config
          cp target/quarry-vision-1.0-SNAPSHOT-shaded.jar dist/app/quarry-vision.jar
          cp -r src/main/resources/application.yaml dist/config/
          cd dist && zip -r ../quarry-vision-${{ github.ref_name }}.zip .
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: quarry-vision-${{ github.ref_name }}.zip
          path: |
            quarry-vision-${{ github.ref_name }}.zip
            target/quarry-vision-1.0-SNAPSHOT-shaded.jar

  publish:
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: quarry-vision-${{ github.ref_name }}
          path: .
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            quarry-vision-${{ github.ref_name }}.zip
            target/quarry-vision-1.0-SNAPSHOT-shaded.jar
