name: Trello Sync

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Create PR with snapshot (otherwise dry-run)"
        type: boolean
        required: false
        default: false
  schedule:
    - cron: "0 5 * * *" # каждый день в 05:00 UTC (08:00 по МСК)

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0         # <-- важно

      - name: Fetch Trello JSON
        env:
          KEY:    ${{ secrets.TRELLO_KEY }}
          TOKEN:  ${{ secrets.TRELLO_TOKEN }}
          BOARD:  ${{ secrets.TRELLO_BOARD_ID }}
        run: |
          curl -sS -L \
            "https://api.trello.com/1/boards/${BOARD}?fields=name,dateLastActivity&lists=open&cards=open&card_fields=name,dateLastActivity,list" \
            -G --data-urlencode "key=${KEY}" --data-urlencode "token=${TOKEN}" \
            -o trello_board.json

      - name: Generate TRELLO.md
        run: |
          python3 - << 'PY'
          import json, pathlib
          j = json.load(open("trello_board.json","r",encoding="utf-8"))
          lists = {l["id"]: l["name"] for l in j.get("lists", [])}
          lines = [
            "# Trello Snapshot",
            f"**Board:** {j.get('name','?')}",
            f"**Updated:** {j.get('dateLastActivity','?')}",
            ""
          ]
          bylist = {}
          for c in j.get("cards", []):
            bylist.setdefault(c.get("idList"), []).append(c)
          for lid, cards in sorted(bylist.items(), key=lambda kv: lists.get(kv[0],'').lower()):
            lines.append(f"## {lists.get(lid,'List')}")
            for c in sorted(cards, key=lambda c: c.get('dateLastActivity','')):
              lines.append(f"- [{c.get('name','')}]  \u2014 _updated {c.get('dateLastActivity','')}_")
            lines.append("")
          pathlib.Path("TRELLO.md").write_text("\n".join(lines), encoding="utf-8")
          PY

      - name: Heartbeat to force diff
        run: |
            mkdir -p .trello-sync
            date -u +"%Y-%m-%dT%H:%M:%SZ run=${GITHUB_RUN_NUMBER} id=${GITHUB_RUN_ID}" > .trello-sync/last-run.txt

      - name: Create PR with snapshot
        if: ${{ inputs.commit == true }}
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/trello-sync-snapshot
          base: main
          title: 'chore: trello snapshot'
          commit-message: 'chore: trello snapshot'
          labels: auto-merge
          delete-branch: true
          token: ${{ secrets.GH_PAT_WORKFLOWS }}
