name: Trello Sync
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ... ваши шаги, которые генерят TRELLO.md / trello_board.json ...

      - name: Create PR with snapshot
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore: trello snapshot"
          body: "Автоснимок доски Trello"
          commit-message: "chore: trello snapshot"
          branch: chore/trello-snapshot
          add-paths: |
            TRELLO.md
            trello_board.json
          delete-branch: true
